# Site settings
title: weiyake
#baseurl: "/weiyake"
#baseurl: <link rel="stylesheet" href={{ "/assets/css/main.css" | relative_url }}>
url: "https://echo0409.github.io"
google_analytics: # Tracking ID, e.g. "UA-000000-01"

# Author
author:
  name: Wei Yake
  #desc: Hello nice to meet you
  email: weiyake@std.uestc.edu.cn
  selfie: assets/img/cat.png

# social
social:
  email: true
  #behance:
  #bitbucket:
  dribbble:
  #facebook: Test
  flickr:
  github: echo0409
  google_plus:
  instagram:
  keybase:
  #linkedin: https://www.linkedin.com/in/kssim/ 
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  gitlab:
  #twitter: Test
  vimeo:
  wordpress:
  youtube:
  #default_txt: "Follow On"

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink: /:year-:month-:day/:title
paginate_path: "/portfolio/page:num/"
paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "READE.md"
  - "screenshot.png"
  

theme: null
